Repository HuijinKang/food-order-management-service, pull requests merged in 2024-11, with the labels that each got.

#12 auth/create-post-signup&post-login
  build.gradle
  src/main/java/org/sparta/foodordermanagementservice/FoodOrderManagementServiceApplication.java
  src/main/java/org/sparta/foodordermanagementservice/common/ApiResponse.java
  src/main/java/org/sparta/foodordermanagementservice/common/WebConfig.java
  src/main/java/org/sparta/foodordermanagementservice/common/WebSecurityConfig.java
  src/main/java/org/sparta/foodordermanagementservice/common/exeption/ErrorCode.java
  src/main/java/org/sparta/foodordermanagementservice/common/exeption/GlobalExceptionHandler.java
  src/main/java/org/sparta/foodordermanagementservice/common/utils/QueryStringEnumConverter.java
  src/main/java/org/sparta/foodordermanagementservice/common/utils/SortedByConverter.java
  src/main/java/org/sparta/foodordermanagementservice/controller/AuthController.java
  src/main/java/org/sparta/foodordermanagementservice/dto/LoginUser.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/LoginRequestDTO.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/OrderListRequestCondition.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/SignupRequestDTO.java
  src/main/java/org/sparta/foodordermanagementservice/dto/response/LoginResponseDTO.java
  src/main/java/org/sparta/foodordermanagementservice/entity/Timestamped.java
  src/main/java/org/sparta/foodordermanagementservice/entity/User.java
  src/main/java/org/sparta/foodordermanagementservice/entity/UserRole.java
  src/main/java/org/sparta/foodordermanagementservice/entity/UserStatus.java
  src/main/java/org/sparta/foodordermanagementservice/repository/UserRepository.java
  src/main/java/org/sparta/foodordermanagementservice/service/AuthService.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImpl.java
  src/main/resources/application.properties
  src/test/java/org/sparta/foodordermanagementservice/FoodOrderManagementServiceApplicationTests.java
  src/test/java/org/sparta/foodordermanagementservice/common/ApiResponseTest.java
  src/test/java/org/sparta/foodordermanagementservice/config/TestConfig.java
  src/test/java/org/sparta/foodordermanagementservice/controller/AuthControllerTest.java
  src/test/java/org/sparta/foodordermanagementservice/repository/UserRepositoryTest.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImplTest.java
Labels: 🌟 feat

#15 user/create-get-user
  src/main/java/org/sparta/foodordermanagementservice/common/WebSecurityConfig.java
  src/main/java/org/sparta/foodordermanagementservice/common/exeption/ErrorCode.java
  src/main/java/org/sparta/foodordermanagementservice/common/exeption/GlobalExceptionHandler.java
  src/main/java/org/sparta/foodordermanagementservice/controller/UserController.java
  src/main/java/org/sparta/foodordermanagementservice/dto/UserDTO.java
  src/main/java/org/sparta/foodordermanagementservice/entity/UserRole.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/UserService.java
  src/test/java/org/sparta/foodordermanagementservice/controller/UserControllerTest.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImplTest.java
Labels: 🌟 feat

#22 auth/fix-deleted-user-issues
  src/main/java/org/sparta/foodordermanagementservice/common/exeption/ErrorCode.java
  src/main/java/org/sparta/foodordermanagementservice/repository/UserRepository.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImpl.java
  src/test/java/org/sparta/foodordermanagementservice/repository/UserRepositoryTest.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImplTest.java
Labels: 🩹 fix

#23 bugfix - API 테스팅 중 발견한 버그 수정
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImpl.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImplTest.java
Labels: 👾 bug, 🩹 fix

#18 user/create-put-user
  src/main/java/org/sparta/foodordermanagementservice/common/exeption/GlobalExceptionHandler.java
  src/main/java/org/sparta/foodordermanagementservice/controller/UserController.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/UpdateUserRequestDTO.java
  src/main/java/org/sparta/foodordermanagementservice/entity/User.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/UserService.java
  src/test/java/org/sparta/foodordermanagementservice/controller/UserControllerTest.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImplTest.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImplTest.java
Labels: 🌟 feat

#19 user/create-patch-role
  src/main/java/org/sparta/foodordermanagementservice/controller/UserController.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/LoginRequestDTO.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/SignupRequestDTO.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/UpdateUserRoleRequestDTO.java
  src/main/java/org/sparta/foodordermanagementservice/entity/User.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/UserService.java
  src/test/java/org/sparta/foodordermanagementservice/controller/UserControllerTest.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImplTest.java
Labels: 🌟 feat

#25 user/bugfix
  src/main/java/org/sparta/foodordermanagementservice/controller/UserController.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/UserService.java
  src/test/java/org/sparta/foodordermanagementservice/controller/UserControllerTest.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImplTest.java
Labels: 👾 bug, 🩹 fix

#26 user/refactoring
  src/main/java/org/sparta/foodordermanagementservice/common/utils/RoleUtils.java
  src/main/java/org/sparta/foodordermanagementservice/controller/UserController.java
  src/test/java/org/sparta/foodordermanagementservice/controller/AuthControllerTest.java
  src/test/java/org/sparta/foodordermanagementservice/controller/UserControllerTest.java
  src/test/java/org/sparta/foodordermanagementservice/repository/UserRepositoryTest.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImplTest.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImplTest.java
Labels: ♻️ refactor

#27 [Feat] User도메인 개발
  src/main/java/org/sparta/foodordermanagementservice/common/WebSecurityConfig.java
  src/main/java/org/sparta/foodordermanagementservice/common/exeption/ErrorCode.java
  src/main/java/org/sparta/foodordermanagementservice/common/exeption/GlobalExceptionHandler.java
  src/main/java/org/sparta/foodordermanagementservice/common/utils/RoleUtils.java
  src/main/java/org/sparta/foodordermanagementservice/controller/UserController.java
  src/main/java/org/sparta/foodordermanagementservice/dto/UserDTO.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/LoginRequestDTO.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/SignupRequestDTO.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/UpdateUserRequestDTO.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/UpdateUserRoleRequestDTO.java
  src/main/java/org/sparta/foodordermanagementservice/entity/User.java
  src/main/java/org/sparta/foodordermanagementservice/entity/UserRole.java
  src/main/java/org/sparta/foodordermanagementservice/repository/UserRepository.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/UserService.java
  src/test/java/org/sparta/foodordermanagementservice/controller/AuthControllerTest.java
  src/test/java/org/sparta/foodordermanagementservice/controller/UserControllerTest.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImplTest.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImplTest.java
Labels: 🌟 feat

#34 [Feat] 리뷰 api 개발
  build.gradle
  src/main/java/org/sparta/foodordermanagementservice/common/AuditorAwareImpl.java
  src/main/java/org/sparta/foodordermanagementservice/common/Config.java
  src/main/java/org/sparta/foodordermanagementservice/common/S3Config.java
  src/main/java/org/sparta/foodordermanagementservice/common/exeption/ErrorCode.java
  src/main/java/org/sparta/foodordermanagementservice/controller/MenuController.java
  src/main/java/org/sparta/foodordermanagementservice/controller/OrderController.java
  src/main/java/org/sparta/foodordermanagementservice/controller/ReviewController.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/MenuRequestDto.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/ReviewListRequestDto.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/ReviewRequestDto.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/SearchRequestDto.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/UpdateMenuRequestDto.java
  src/main/java/org/sparta/foodordermanagementservice/dto/response/MenuResponseDto.java
  src/main/java/org/sparta/foodordermanagementservice/dto/response/ReviewResponseDto.java
  src/main/java/org/sparta/foodordermanagementservice/entity/BaseEntity.java
  src/main/java/org/sparta/foodordermanagementservice/entity/FileContentType.java
  src/main/java/org/sparta/foodordermanagementservice/entity/Menu.java
  src/main/java/org/sparta/foodordermanagementservice/entity/MenuStatus.java
  src/main/java/org/sparta/foodordermanagementservice/entity/Review.java
  src/main/java/org/sparta/foodordermanagementservice/entity/User.java
  src/main/java/org/sparta/foodordermanagementservice/repository/MenuCustomRepository.java
  src/main/java/org/sparta/foodordermanagementservice/repository/MenuCustomRepositoryImpl.java
  src/main/java/org/sparta/foodordermanagementservice/repository/MenuRepository.java
  src/main/java/org/sparta/foodordermanagementservice/repository/ReviewRepository.java
  src/main/java/org/sparta/foodordermanagementservice/service/ImageService.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/ImageServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/MenuServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/ReviewServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/StoreServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImpl.java
  src/main/java/org/sparta/foodordermanagementservice/service/MenuService.java
  src/main/java/org/sparta/foodordermanagementservice/service/ReviewService.java
  src/main/java/org/sparta/foodordermanagementservice/service/StoreService.java
  src/main/java/org/sparta/foodordermanagementservice/service/UserService.java
  src/main/resources/application.properties
  src/test/java/org/sparta/foodordermanagementservice/repository/UserRepositoryTest.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/AuthServiceImplTest.java
  src/test/java/org/sparta/foodordermanagementservice/service/Impl/UserServiceImplTest.java
Labels: 🌟 feat

#29 googleapi/feat-generate-menu-description
  src/main/java/org/sparta/foodordermanagementservice/common/Config.java
  src/main/java/org/sparta/foodordermanagementservice/controller/GoogleAPIController.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/GeminiRequestDTO.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/MenuDescriptionGenerateRequestDTO.java
  src/main/java/org/sparta/foodordermanagementservice/dto/request/UpdateUserRequestDTO.java
  src/main/java/org/sparta/foodordermanagementservice/dto/response/GeminiResponseDTO.java
  src/main/java/org/sparta/foodordermanagementservice/dto/response/MenuDescriptionGenerateResponseDTO.java
  src/main/java/org/sparta/foodordermanagementservice/entity/AiApiLog.java
  src/main/java/org/sparta/foodordermanagementservice/repository/AiApiLogRepository.java
  src/main/java/org/sparta/foodordermanagementservice/service/GoogleApiService.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/GoogleApiServiceImpl.java
  src/main/resources/application.properties
  src/test/java/org/sparta/foodordermanagementservice/controller/GoogleAPIControllerTest.java
Labels: 🌟 feat

#38 fix - 테스트 코드에 entity listener 설정
  src/main/java/org/sparta/foodordermanagementservice/entity/AiApiLog.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/GoogleApiServiceImpl.java
  src/main/resources/application.properties
Labels: 🩹 fix

#41 [Fix] 환경변수 수정
  build.gradle
  src/main/java/org/sparta/foodordermanagementservice/common/S3Config.java
  src/main/java/org/sparta/foodordermanagementservice/service/Impl/ImageServiceImpl.java
  src/main/resources/application.properties
  src/test/java/org/sparta/foodordermanagementservice/FoodOrderManagementServiceApplicationTests.java
Labels: 🩹 fix
